spring:
  data:
    redis:
      host: ${REDIS_HOST:192.168.194.250}
      port: ${REDIS_PORT:6379}
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:192.168.194.250:9092}
    consumer:
      group-id: proxy-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    ROOT: INFO
    com.celi.proxy: DEBUG
    org.springframework.kafka: INFO
    org.springframework.data.redis: DEBUG

application:
  backend:
    url: ${BACKEND_URL:http://localhost:8080}
